const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const context = { console, document: { readyState: 'loading', addEventListener() {} } };
context.window = context;
vm.createContext(context);
for (const file of ['js/constants-2026.js', 'js/loan.js']) vm.runInContext(fs.readFileSync(path.join(root, file), 'utf8'), context);
const calculator = context.MoneyCalcCalculators.loan;
const methods = context.CALC_CONSTANTS_2026.LOAN.METHODS;
const input = { principal: 12000000, annualRate: 6, termMonths: 12, graceMonths: 0 };
const equal = calculator.buildRepaymentSchedule({ ...input, method: methods.EQUAL_PRINCIPAL });
const bullet = calculator.buildRepaymentSchedule({ ...input, method: methods.BULLET });
assert.equal(equal.firstPayment, 1060000);
assert.equal(equal.lastPayment, 1005000);
assert.equal(equal.totalInterest, 390000);
assert.equal(bullet.firstPayment, 60000);
assert.equal(bullet.lastPayment, 12060000);
assert.equal(bullet.totalInterest, 720000);
const html = fs.readFileSync(path.join(root, 'loan/index.html'), 'utf8');
for (const value of [equal.firstPayment, equal.lastPayment, equal.totalInterest, bullet.firstPayment, bullet.lastPayment, bullet.totalInterest]) assert.ok(html.includes(value.toLocaleString('ko-KR') + '원'));
assert.ok(html.includes('날짜별 일할 계산'));
console.log('Loan article examples match both production repayment schedules.');
